[[CURRENCIES]]
code="EXO"
issuer="GBQBSLLQL2IWYOVNQ6UUFU7G2YROVNRKBY2QTIP6MAMW2FMUKXEW5EXO"
display_decimals=7
name="Token for Trusti Certification"
desc="Blockchain based data certification."
anchor_asset="EXO"
anchor_asset_type="Token"
